apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: springboot-endtoend-application
spec:
  selector:
    matchLabels:
      app: springboot-endtoend-application
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springboot-endtoend-application
    spec:
      containers:
        - name: springboot-endtoend-application
          image: srinu255/springboot-endtoend-application:latest  # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster